events {}
http {
    upstream users_service {
        server users:8080;
    }

    upstream books_service {
        server books:8080;
    }

    upstream borrow_service {
        server borrow:8080;
    }

    upstream docs_service {
        server docs:8080;
    }

    server {
        listen 8080;


        # Authentication Routes (Users Service)
        location /auth {
            proxy_pass http://users_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Users Routes (Users Service)
        location /users {
            proxy_pass http://users_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Books Routes (Books Service)
        location /books {
            proxy_pass http://books_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Borrow Routes (Borrow Service)
        location /borrow {
            proxy_pass http://borrow_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # OpenAPI Specs
        location /users/openapi.json {
            proxy_pass http://users_service/openapi.json;
            proxy_set_header Host $host;
        }
        location /books/openapi.json {
            proxy_pass http://books_service/openapi.json;
            proxy_set_header Host $host;
        }
        location /borrow/openapi.json {
            proxy_pass http://borrow_service/openapi.json;
            proxy_set_header Host $host;
        }

        # Docs Service
        location /docs {
            proxy_pass http://docs_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
